version: '3'

services:

  php:
    build: ./docker/php
    volumes:
      - ./project:/project
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom-php.ini

    depends_on:
      - db

  db:
    image: mariadb:10.3.30-focal
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: toor
      TZ: Europe/Prague
    volumes:
      - ./config/mysql.cnf:/etc/mysql/conf.d/local.cnf
      - ./data/db:/var/lib/mysql
    ports:
      - '3308:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - "8089:8080"
    links:
      - db:db
    environment:
      - ADMINER_DESIGN=nette
    volumes:
      - ./config/adminer.ini:/usr/local/etc/php/conf.d/uploads.ini

  web:
    image: nginx:mainline-alpine
    restart: always
    depends_on:
      - php
    volumes:
      - ./project:/project
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
      args:
        WORK_DIR: "/var/www/html"
    command: /var/www/cache/entrypoint.sh /var/www/html
    volumes:
      - "./app:/var/www/html"
      - "./docker/node/entrypoint.sh:/var/www/html/../cache/entrypoint.sh"
    ports:
      - "3005:3000"
    environment:
      NODE_ENV: development
      TZ: Europe/Warsaw
    deploy:
      resources:
        limits:
          memory: 1g

  elasticsearch:
    build:
      context: docker/elasticsearch/
      args:
        ELK_VERSION: 8.8.0
    ports:
      - "9205:9200"
      - "9305:9300"
    environment:
      TZ: Europe/Warsaw
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: zaq1@WSX
    depends_on:
      web:
        condition: service_started
  logstash:
    build:
      context: docker/logstash/
      args:
        ELK_VERSION: 8.8.0
    ports:
      - "1235:5000"
      - "9605:9600"
    expose:
      - "5044"
    environment:
      TZ: Europe/Warsaw
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
  kibana:
    build:
      context: docker/kibana/
      args:
        ELK_VERSION: 8.8.0
    ports:
      - "5605:5601"
    environment:
      TZ: Europe/Warsaw
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
      ELASTICSEARCH_USERNAME: admin
      ELASTICSEARCH_PASSWORD: zaq1@WSX
    depends_on:
      - elasticsearch
  filebeat:
    build:
      context: docker/filebeat/
      args:
        ELK_VERSION: 8.8.0
    entrypoint: "filebeat -e -strict.perms=false"
    environment:
      TZ: Europe/Warsaw
    volumes:
      - "./docker/nginx/log:/var/log/nginx:ro"
    depends_on:
      logstash:
        condition: service_started
      elasticsearch:
        condition: service_started
      kibana:
        condition: service_started
    links:
      - logstash
